[package]
name = "integrationos-emit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
axum.workspace = true
dotenvy.workspace = true
envconfig.workspace = true
fluvio = { version = "0.23.3", features = ["admin"] }
futures-util.workspace = true
futures.workspace = true
http-serde-ext.workspace = true
http.workspace = true
integrationos-domain = { path = "../integrationos-domain" }
serde = { workspace = true , features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
