[package]
name = "watchdog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
dotenvy.workspace = true
envconfig.workspace = true
integrationos-domain.workspace = true
tokio.workspace = true
tracing.workspace = true

