on: pull_request

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
        id: rust-cache
      - name: Check for cache hit
        run: echo "cache-hit=${{ steps.rust-cache.outputs.cache-hit }}"
      - run: cargo fmt --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        id: rust-cache
      - name: Check for cache hit
        run: echo "cache-hit=${{ steps.rust-cache.outputs.cache-hit }}"
      - run: cargo check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        id: rust-cache
      - name: Check for cache hit
        run: echo "cache-hit=${{ steps.rust-cache.outputs.cache-hit }}"
      - run: cargo clippy

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Remove cached stuff
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v4
      - name: Starting up Docker 🐳
        run: ls && docker compose -f ./integrationos-emit/tests/resource/docker-compose.yml up -d
      - name: Install fluvio CLI
        run: curl -fsS https://hub.infinyon.cloud/install/install.sh | bash
      - name: Create fluvio topic
        run: ~/.fluvio/bin/fluvio profile add docker 127.0.0.1:9103 docker && ~/.fluvio/bin/fluvio topic create events && ~/.fluvio/bin/fluvio topic create dlq
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        id: rust-cache
      - name: Check for cache hit
        run: echo "cache-hit=${{ steps.rust-cache.outputs.cache-hit }}"
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - run: cargo nextest run --all-features
